### PR TITLE
Feat/products page

### PR DESCRIPTION
**Pull request by Snigdha17**

### CODE REVIEW

**Review by dev-enforced — APPROVED** [review]

**Review by MonikaJhingan — APPROVED** [review]
The code looks really nice, and needs to be merged.

**Review by Sindhu983 — APPROVED** [review]
Looking good go for merge

**Review by Sindhu983 — APPROVED** [review]
cool

**Review by Mandhularajitha — APPROVED** [review]
Remove extra spaces after u can murge

**Pull request merged**
